
---

- name: download bosh cli
  get_url:
    url: 'https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-2.0.45-linux-amd64'
    dest: /usr/local/bin/bosh
    mode: 0755

- name: execute bosh
  command: bosh -v

- name: upgrade apt
  apt: upgrade=dist

- name: install bosh depends on
  apt: name={{ item }}
  with_items:
    - build-essential
    - zlibc
    - zlib1g-dev
    - ruby
    - ruby-dev
    - openssl
    - libxslt-dev
    - libxml2-dev
    - libssl-dev
    - libreadline6
    - libreadline6-dev
    - libyaml-dev
    - libsqlite3-dev
    - libpq-dev
    - libmysqlclient-dev
    - sqlite3
    - expect
    - tcl
    - git