---

- name: create ecs instance and build network environment
  hosts: localhost
  tasks:
    - shell: terraform init
      args:
        chdir: ./server

    - expect:
        command: terraform destroy -var 'alicloud_access_key={{ alicloud_access_key }}' -var 'alicloud_secret_key={{ alicloud_secret_key }}' -var 'alicloud_region={{ alicloud_region }} -var 'domain_name={{system_domain}}'
        responses:
          'Enter a value:' : 'yes'
        chdir: ./server
      when: delete

    - shell: terraform apply -var 'alicloud_access_key={{ alicloud_access_key }}' -var 'alicloud_secret_key={{ alicloud_secret_key }}' -var 'alicloud_region={{ alicloud_region }}' -var 'domain_name={{system_domain}}'
      args:
        chdir: ./server
      when: not delete

- name: deploy cf
  hosts: CloudFoundaryServer
  remote_user: root
  roles:
    - bosh-cli
    - bosh-deploy
    - cf-deploy
    - app-deploy
