---

- name: create downloads
  file: path="{{ download_dir }}" state=directory

- name: create bosh-init
  file: path="{{ bosh_deploy_dir }}" state=directory

- name: git clone bosh deployment
  git:
    repo: 'https://github.com/aliyun/bosh-deployment.git'
    dest: '{{ bosh_deploy_dir }}/bosh-deployment'
    version: alicloud

- name: deploy bosh
  shell: '{{ item }}'
  args:
    chdir: '{{ bosh_deploy_dir }}'
  with_items:
    - export BOSH_DIRECTOR_IP={{ internal_ip }}
    - echo export BOSH_DIRECTOR_IP={{ internal_ip }} >> /etc/profile
    - . /etc/profile
    - bosh create-env bosh-deployment/bosh.yml --state=state.json --vars-store=creds.yml -o bosh-deployment/alicloud/cpi.yml -o bosh-deployment/jumpbox-user.yml -o bosh-deployment/misc/powerdns.yml -v dns_recursor_ip={{dns_recursor_ip}} -v download_dir={{download_dir}} -v director_name={{director_name}} -v internal_cidr={{internal_cidr}} -v internal_gw={{internal_gw}} -v internal_ip={{internal_ip}} -v vswitch_id={{vswitch_id}} -v security_group_id={{security_group_id}} -v access_key_id={{alicloud_access_key}} -v access_key_secret={{alicloud_secret_key}} -v region={{alicloud_region}} -v access_endpoint=aliyuncs.com -v zone={{bosh_zone}}
    - bosh int ./creds.yml --path /director_ssl/ca > ca-cert
    - bosh alias-env my-bosh -e {{ internal_ip }} --ca-cert ca-cert
    - bosh int ./creds.yml --path /admin_password > password
    - bosh int ./creds.yml --path /jumpbox_ssh/private_key > jumpbox.key
    - chmod 600 jumpbox.key

- name: get password
  command: awk 'NR==1{print}' password
  args:
    chdir: '{{ bosh_deploy_dir }}'
  register: secret_key


- name: set secret key and login
  shell: '{{ item }}'
  args:
    chdir: '{{ bosh_deploy_dir }}'
  with_items:
      - echo export BOSH_LOG_LEVEL=info >> /etc/profile
      - echo export BOSH_LOG_PATH=$(pwd)/bosh.log >> /etc/profile
      - echo export BOSH_ENVIRONMENT={{internal_ip}}
      - echo export BOSH_CA_CERT=$(pwd)/ca-cert >> /etc/profile
      - echo export BOSH_CLIENT=admin >> /etc/profile
      - echo export BOSH_CLIENT_SECRET={{ secret_key.stdout }} >> /etc/profile
      - . /etc/profile
      - echo bosh -e {{director_name}} l \<\< EOF > bosh_login.sh
      - echo admin >> bosh_login.sh
      - echo {{ secret_key.stdout }} >> bosh_login.sh
      - echo EOF >> bosh_login.sh
      - chmod +x bosh_login.sh
      - ./bosh_login.sh
      - bosh -e my-bosh vms
