---

- name: make dir
  file: path="{{ cf_deploy_dir }}" state=directory

- name: copy cloud-config
  copy:
    src: cloud-config.yml
    dest: '{{ cf_deploy_dir }}'

- name: copy convert
  copy:
    src: convert.sh
    dest: '{{ cf_deploy_dir }}'
    mode: 0777

- name: update config
  shell: '{{ item }}'
  args:
    chdir: '{{ cf_deploy_dir }}'
  with_items:
    - echo bosh -e my-bosh update-cloud-config ./cloud-config.yml -v zone-1={{zone_1}} -v zone-2={{zone_2}} -v zone-3={{zone_3}} -v subnet-1-id={{vswitch_id_1}} -v subnet-2-id={{vswitch_id_2}} -v subnet-3-id={{vswitch_id_3}} -v subnet-1-range={{vswitch_range_1}}  -v subnet-2-range={{vswitch_range_2}} -v subnet-3-range={{vswitch_range_3}} -v subnet-1-gateway={{vswitch_gateway_1}} -v subnet-2-gateway={{vswitch_gateway_2}} -v subnet-3-gateway={{vswitch_gateway_3}} -v security-group-id={{security_group_id}} -v tcp-slb-id={{tcp_slb_id}} -v http-slb-id={{http_slb_id}} \<\< EOF > update_config.sh
    - echo y >> update_config.sh
    - echo EOF >> update_config.sh
    - chmod +x update_config.sh
    - ./update_config.sh
  args:
    chdir: '{{ cf_deploy_dir }}'

- name: git clone cf deployment
  git:
    repo: 'https://github.com/aliyun/cf-deployment.git'
    dest: '{{ cf_deploy_dir }}/cf-deployment'

- name: deploy cf
  shell: '{{ item }}'
  args:
    chdir: '{{cf_deploy_dir}}'
  with_items:
    - bosh -e my-bosh vms
    - bosh -e my-bosh upload-stemcell http://bosh-alicloud.oss-cn-hangzhou.aliyuncs.com/light-bosh-stemcell-{{stemcell_version}}-alicloud-kvm-ubuntu-trusty-go_agent.tgz
    - bosh -e my-bosh upload-release https://bosh.io/d/github.com/cloudfoundry/cf-release?v={{ cf_release_version }}
    - export CF_DOMAIN={{system_domain}}
    - echo export CF_DOMAIN={{system_domain}} >> /etc/profile
    - . /etc/profile
    - ./convert.sh {{cf_release_version}} {{stemcell_version}} cf-deployment/cf-deployment.yml
    - echo bosh -e my-bosh -d cf deploy cf-deployment-{{cf_release_version}}.yml --vars-store cf-vars.yml -v system_domain={{system_domain}} \<\< EOF > deploy_cf.sh
    - echo yes >> deploy_cf.sh
    - echo EOF >> deploy_cf.sh
    - chmod +x deploy_cf.sh
    - ./deploy_cf.sh


- name: download cf cli and unarchive
  unarchive:
    src: 'https://cli.run.pivotal.io/stable?release=linux64-binary&source=github'
    dest: '{{ download_dir }}'
    remote_src: yes

- name: install cf cli
  shell: '{{ item }}'
  args:
    chdir: '{{ download_dir }}'
  with_items:
    - mv cf /usr/local/bin
    - sudo curl -o /usr/share/bash-completion/completions/cf https://raw.githubusercontent.com/cloudfoundry/cli/master/ci/installers/completion/cf
