azs:
- name: z1
  cloud_properties:
    availability_zone: ((zone-1))
- name: z2
  cloud_properties:
    availability_zone: ((zone-2))
- name: z3
  cloud_properties:
    availability_zone: ((zone-3))

vm_types:
- name: minimal
  cloud_properties:
    instance_type: ecs.mn4.small
    ephemeral_disk: {size: "51_200"}
- name: small
  cloud_properties:
    instance_type: ecs.sn2.medium
    ephemeral_disk: {size: "51_200"}
- name: default
  cloud_properties:
    instance_type: ecs.sn2.medium
    ephemeral_disk: {size: "51_200"}
- name: small-highmem
  cloud_properties:
    instance_type: ecs.sn2ne.xlarge
    ephemeral_disk: {size: "51_200"}
- name: compiler
  cloud_properties:
    instance_type: ecs.sn1.large
    ephemeral_disk: {size: "51_200"}

disk_types:
- name: 5GB
  disk_size: 20_480
- name: 10GB
  disk_size: 20_480
- name: 100GB
  disk_size: 102_400

vm_extensions:
- name: 5GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: {size: "20_480"}
- name: 10GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: {size: "20_480"}
- name: 50GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: {size: "50_120"}
- name: 100GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: {size: "102_400"}
- name: 500GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: {size: "512_000"}
- name: 1TB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: {size: "1024_000"}
- name: cf-router-network-properties
  cloud_properties:
    slbs: ["((http-slb-id))"]
- name: cf-tcp-router-network-properties
  cloud_properties:
    slbs: ["((tcp-slb-id))"]
- name: diego-ssh-proxy-network-properties

networks:
- name: default
  type: manual
  subnets:
  - range: ((subnet-1-range))
    gateway: ((subnet-1-gateway))
    az: z1
    dns: [8.8.8.8]
    cloud_properties:
      vswitch_id: ((subnet-1-id))
      security_group_id: ((security-group-id))
  - range: ((subnet-2-range))
    gateway: ((subnet-2-gateway))
    az: z2
    dns: [8.8.8.8]
    cloud_properties:
      vswitch_id: ((subnet-2-id))
      security_group_id: ((security-group-id))
  - range: ((subnet-3-range))
    gateway: ((subnet-3-gateway))
    az: z3
    dns: [8.8.8.8]
    cloud_properties:
      vswitch_id: ((subnet-3-id))
      security_group_id: ((security-group-id))
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: compiler
  network: default
